name: mapgwm
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipython
  - jupyter
  - notebook
  - ipykernel
  - matplotlib
  - pyyaml
  - numpy<1.20
  - scipy
  - xarray
  - netcdf4
  - pandas<2.0
  - openpyxl
  - gdal
  - fiona
  - rasterio
  - rasterstats
  - shapely
  - rtree
  - pyproj
  - pyshp
  - xlrd
  - pip
  - pip:
    - gis-utils
  - git+https://github.com/modflowpy/flopy@develop
  - git+https://github.com/usgs/sfrmaker@develop
  - git+https://github.com/usgs/modflow-setup@develop
  - git+https://github.com/aleaf/modflow-export@develop


