name: test
channels:
- conda-forge
- defaults
- atleaf
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib
- pyyaml
- numpy
- scipy
- xarray
- netcdf4
- pandas
- openpyxl
- gdal
- fiona
- rasterio
- rasterstats
- shapely
- rtree
- pyproj>=2.2
- pyshp
- codecov
- coverage
- flake8
- pytest
- sphinx
- numpydoc
- nbsphinx  # for rendering notebooks in sphinx-generated docs
- sphinx-copybutton
- sphinx_rtd_theme
- pip
- pip:
  - gis-utils
  - doctr
  - git+https://github.com/modflowpy/flopy@develop
  - git+https://github.com/aleaf/sfrmaker@develop
  - git+https://github.com/aleaf/modflow-setup@develop
  - git+https://github.com/aleaf/modflow-export@develop

